apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-deployment
  namespace: default
  labels:
    app: dm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dm
  template:
    metadata:
      labels:
        app: dm
    spec:
      containers:
        - name: dm-cont1
          image: mohanudayana/dm
          ports:
            - containerPort: 80
